name: secure_rsa
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  encrypt: ^5.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
